### ISSUE TITLE
The / (slash) character at the end of non closing tags 

### ISSUE THREAD

**Issue by Bam92** [flaviocopes/html-handbook#16]
I've received your email to proofread you next publication. That's very good, and it's a free of charge e-book.
I see that you're using HTML 5. So, is it still important to use ```/``` character at the end of the closing tag? E.g.:
```<input type="text" />```
I personally prefer this: ```<input type="text">``` (what is used by almost everyone).
What I propose is just to tell reader that it's optional. You can either use it or not so that they can't be confused when they see some other HTML codes that do not follow that rule of adding slash to tags that don't have corresponding closing tags.

**Comment by flaviocopes** [comment]
Good point! I should not add it, as it can be confusing.

It's a habit of mine. Going to fix this!
